In [1]:
# NumPy 中处理数字的最常见方式是通过 ndarray 对象。它们与 Python 列表相似，但是可以有任意数量的维度。
# 由于它可以存储任意数量的维度，你可以使用 ndarray 来表示任意数据类型：标量、向量、矩阵或张量。

In [2]:
import numpy as np

# 标量

In [3]:
# NumPy 中的标量 比 Python 中的标量类型更多。不像 Python 只有基本类型 int、float 等，NumPy 可以让你指定有符号和无符号的类型以及不同的大小。因此，除了 Python 的 int，你可以使用 uint8、int8、uint16、int16 等类型。

# 这些类型很重要，因为你所创建的每个对象（向量、矩阵、张量）最终都会存储标量。而且，当你创建 NumPy 数组时，可以指定类型 - 但是数组中的每一项必须具有相同的类型。在这方面，NumPy 数组更像是 C 数组，而非 Python 列表。

# 如果要创建一个包含标量的 NumPy 数组，方法是将值传递给 NumPy 的 array 函数，如下所示：

In [4]:
s = np.array(5)

In [5]:
s.shape

()

In [6]:
# s.shape返回()表示0维

In [7]:
# 可以在 ndarray、NumPy 标量和普通的 Python 标量之间执行数学运算

In [8]:
x = s + 3

In [9]:
x

8

In [10]:
type(x)

numpy.int64

In [11]:
type(s)

numpy.ndarray

# 向量

In [12]:
# 要创建一个向量，你可以将 Python 列表传递给 array 函数，像这样：

In [13]:
v = np.array([1,2,3])

In [14]:
v.shape

(3,)

In [15]:
x = v[1]

In [16]:
x

2

In [20]:
print v[:2]

[1 2]


# 矩阵

In [21]:
# 使用 NumPy 的 array 函数创建矩阵，跟创建向量一样。但是，这次你不只是传入一个列表，而是提供列表的列表，其中每个列表代表一行。
# 所以要创建一个包含数字 1 到 9 的 3x3 矩阵，你可以这样做：

In [22]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [23]:
m.shape

(3, 3)

In [24]:
print m[1][2]

6


# 张量

In [25]:
# 张量与向量和矩阵一样，但张量可以有更多的维度。例如，要创建一个 3x3x2x1 的张量，你可以这样做：

In [26]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [27]:
t.shape

(3, 3, 2, 1)

In [28]:
print t[2][1][1][0] 

16


# 更改现状

In [29]:
v = np.array([1,2,3,4])

In [30]:
v.shape

(4,)

In [31]:
x = v.reshape(1,4)

In [32]:
x

array([[1, 2, 3, 4]])

In [33]:
x.shape

(1, 4)

In [34]:
# 关于更改 NumPy 数组的形状还有一点：如果你看到经验丰富的 NumPy 使用者的代码，经常会看到他们使用一种特殊的切片语法，
# 而不是调用 reshape。使用该语法，前面的两个示例会是这样的：

In [35]:
x = v[None, :]

In [36]:
# 或者

In [37]:
x = v[:, None]

In [38]:
x.shape

(4, 1)

In [39]:
# 这些代码创建一个切片，查看 v 的所有项目，要求 NumPy 为相关轴添加大小为 1 的新维度。
# 你现在看起来可能觉得很奇怪，但它是一种常见的技术，所以了解它没什么坏处。

# 元素级运算

In [40]:
values = [1,2,3,4,5]

In [41]:
values = np.array(values) + 5  # 转换为NumPy方式

In [44]:
values += 10

In [45]:
values

array([16, 17, 18, 19, 20])

In [46]:
val = np.array([1,2,3])

In [47]:
val = np.multiply(val, 10)

In [48]:
val

array([10, 20, 30])

In [49]:
val *= 2

In [50]:
val

array([20, 40, 60])

In [51]:
# 元素级矩阵运算

In [52]:
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])

In [53]:
a + b

array([[ 3,  7],
       [11, 15]])

In [54]:
a * b

array([[ 2, 12],
       [30, 56]])

# 矩阵乘法

In [55]:
# 关于矩阵乘法的重要提醒
# 左侧矩阵的列数必须等于右侧矩阵的行数。
# 答案矩阵始终与左侧矩阵有相同的行数，与右侧矩阵有相同的列数。
# 顺序很重要：乘法A•B不等于乘法B•A。
# 左侧矩阵中的数据应排列为行，而右侧矩阵中的数据应排列为列。
# 记住这四点，你在构建神经网络时，就能搞清楚如何正确排列矩阵乘法了。

In [ ]:
# -- 元素级乘法

In [56]:
m = np.array([[1,2,3],[4,5,6]])
n = m * 0.25

In [57]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
n

array([[ 0.25,  0.5 ,  0.75],
       [ 1.  ,  1.25,  1.5 ]])

In [59]:
m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [60]:
np.multiply(m, n)

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [61]:
# -- 矩阵乘积

In [62]:
# 要获得矩阵乘积，你可以使用 NumPy 的 matmul 函数。

In [63]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [65]:
a.shape

(2, 4)

In [66]:
b.shape

(4, 3)

In [67]:
c = np.matmul(a,b)

In [68]:
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [69]:
c.shape

(2, 3)

In [70]:
np.matmul(b,a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

In [71]:
# 左侧矩阵的列数必须等于右侧矩阵的行数。

In [72]:
# -- dot函数

In [73]:
#如果矩阵是二维的，那么 dot 和 matmul 函数的结果是相同的。

In [74]:
np.dot(a,b)

array([[ 70,  80,  90],
       [158, 184, 210]])

# 转置

In [75]:
# 在 NumPy 中获得矩阵的转置非常容易。只需访问其 T 属性即可。

In [76]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [77]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [79]:
# NumPy 在进行转置时不会实际移动内存中的任何数据 - 只是改变对原始矩阵的索引方式 - 所以是非常高效的。

In [81]:
# 但是，这也意味着你要特别注意修改对象的方式，因为它们共享相同的数据。例如，对于上面同一个矩阵 m，我们来创建一个新的变量 m_t 来存储 m 的转置。
# 然后看看如果我们修改 m_t 中的值，会发生什么：

In [82]:
m_t = m.T

In [83]:
m_t

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [84]:
m_t[3][1] = 200

In [85]:
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [86]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

In [87]:
#  注意它是如何同时修改转置和原始矩阵的！这是因为它们共享相同的数据副本。所以记住，将转置视为矩阵的不同视图，而不是完全不同的矩阵。

In [88]:
# 需要用到转置的用例

In [89]:
# 假设你有以下两个矩阵，称为 inputs 和 weights，

In [90]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])

In [91]:
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [92]:
type(inputs)

numpy.ndarray

In [93]:
inputs.shape

(1, 4)

In [94]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [95]:
weights.shape

(3, 4)

In [96]:
np.matmul(inputs, weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [97]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [98]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])